version: '3.9'

services:
  # DATABASE - POSTGRESQL
  # Setup for the PostgreSQL database service
  postgres:
    container_name: db-postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME} 
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data 
    networks:
      - app

  # SERVER - NESTJS
  # Configuration for the NestJS server service.
  dev:
    container_name: nestjs-server
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    working_dir: /app
    networks:
      - app 
    ports:
      - 3000:3000
    depends_on:
      - postgres 
    command: [sh, -c, 'pnpm run start:dev']
    volumes:
      - .:/app:delegated

networks: 
  app:

volumes:
  pg-data:  # PERSISTENT VOLUME POSTGRESQL - DB
