.PHONY: migrate-create migrate-run migrate-revert

# Create a new migration with a name provided by the variable name.
# Usage: make migrate-create name=CreateUsersTable
#FIX:  Dont work, fix later
migrate-create:
	docker-compose exec dev pnpm run typeorm migration:create -n $(name)

# Run migrations
migrate-run:
	docker-compose exec dev pnpm run migration:run

# Revert the last migration
migrate-revert:
	docker-compose exec dev pnpm run migration:revert

# Generate a migration based on changes you made to the entities
# TODO: Should I implement that too ? Dont have it in packagejson
# Usage: make migrate-generate name=AutoGeneratedMigration
# migrate-generate:
# 	docker-compose exec dev pnpm run typeorm migration:generate -n $(name)

