.PHONY: migrate-run migrate-revert test

# Run migrations
migrate-run:
	docker-compose exec dev pnpm run migration:run

# Revert the last migration
migrate-revert:
	docker-compose exec dev pnpm run migration:revert

# Generate a migration based on changes you made to the entities
# HACK: Should I implement that too ? Dont have it in packagejson
# Usage: make migrate-generate name=AutoGeneratedMigration
# migrate-generate:
# 	docker-compose exec dev pnpm run typeorm migration:generate -n $(name)

test:
	docker-compose exec dev pnpm run test
